Repository sophtank/3155finalproj, pull requests merged in 2024-05, with the labels that each got.

#69 Images are functional now
  app.py
  requirements.txt
  templates/createdrive.html
  templates/editdrive.html
Labels: enhancement

#75 checked over good ole .py files formatted everything as well
  app.py
  repositories/Vehicle.py
  repositories/deleteSql.py
  repositories/drives.py
  repositories/edit_drive.py
  repositories/leaderboard.py
  repositories/loginSql.py
  repositories/userProfileSql.py
  repositories/viewDrives.py
  repositories/viewIndividualDrive.py
Labels: documentation

#74 Drives photo change
  final_project_schema.sql
  static/Styles/individualDrive.css
  templates/individualDrive.html
Labels: enhancement

#76 Styling fix
  static/Scripts/comments.js
  static/Styles/UserProfile.css
  static/Styles/index.css
  templates/LeaderBoard.html
  templates/UserProfile.html
  templates/_layout.html
  templates/index.html
  templates/individualDrive.html
  templates/login.html
  templates/signup.html
  templates/viewDrives.html
Labels: bug
